### ISSUE TITLE
Backtracking von Zuker

### ISSUE THREAD

**Issue by heidi1303** [alexander-scholz/study#11]
Sagt mal, warum testen wir beim Zuker-Backtracking, "if F(i,j) == F(**i, j-1**); else i is paired"? Macht das Sinn?
Ist das inkonsistent und müsste eigentlich heißen "if F(i,j) == F(**i+1, j**); else i is paired"?
Wie seht ihr das @sojwolf @alexander-scholz @TheGermanDuke @kraemer-stefan ?

**Comment by alexander-scholz** [comment]
Hallo zusammen,

ich habe das gerade mal mit Stefan beredet... wir gehen mit **F(i+1, j)** mit

**Comment by heidi1303** [comment]
Ok, PR #13
