### ISSUE TITLE
Konsistenz von Zuker-Bild, Zuker-Rekurrenzen, McCaskill-Rekurrenzen

### ISSUE THREAD

**Issue by heidi1303** [alexander-scholz/study#16]
Tach!
der Cartoon vom Zuker-Algorithmus (vom Ronny) stimmt ja mit den Indizes nicht mehr ganz mit den unten drunter aufgeschriebenen Rekurrenzen überein. Dann stimmts außerdem nicht mehr ganz mit dem Backtracking - und auch nicht mit McCaskill. 
Das sind jeweils nur ganz kleine Veränderungen, aber wir wollten's ja - wenn möglich - besser machen, deshalb schlage ich vor, das zu vereinheitlichen.
Da wir das schöne Bildchen haben (und Bernie das mal so, mal so gemacht hat) würde ich das Bild als Vorlage nehmen und die Formeln daran anpassen.
Seid ihr damit einverstanden @alexander-scholz @TheGermanDuke @kraemer-stefan @sojwolf ?

**Comment by alexander-scholz** [comment]
Also wenn du den Durchblick hast dann mach es ;-)

**Comment by heidi1303** [comment]
OK!
Oh Ronny... -.-
![screenshot_20160717_223136](https://cloud.githubusercontent.com/assets/11767963/16902919/59705098-4c6e-11e6-928c-89b13f4c93b9.png)

**Comment by kraemer-stefan** [comment]
Sehr gute Idee! Und aus Gründen der Verständlichkeit auch didaktisch die beste Entscheidung :).

**Comment by kraemer-stefan** [comment]
Hey Alex hast du passende Bildchen auch für den Mc Caskill, sonst würde ich mich darum mal kümmern??

**Comment by heidi1303** [comment]
Ich pushe demnächst mal die neuen Indizes, nur, bevor sich jemand doppelte Arbeit macht...

**Comment by kraemer-stefan** [comment]
Ja, hab mir gerade Mc Caskill noch einmal angesehen und gemerkt, dass ich da ganz schönen Mist in das Skript eingefügt habe... Also ich schau mir das dann einfach in der dann aktuellsten Variante an... :)

**Comment by alexander-scholz** [comment]
@kraemer-stefan : du hast Mist bei McCaskill eingefügt? Das habe ich doch erst Freitag nacht fertig gemacht???

**Comment by kraemer-stefan** [comment]
meine auch sankoff^^

Ach alles die gleichen Algorithmen nur mit anderen Namen XD...
